StackOverflow.Web/Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using StackOverflow.Data;
using StackOverflow.Domain.Entities;
using StackOverflow.Web.Models;

namespace StackOverflow.Web.Controllers
{
    public class AnswerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AnswerController()
        {
            _unitOfWork = new UnitOfWork();
        }
        // GET: Answer
        public ActionResult AnswerIndex(IEnumerable<AnswerModel> models, string error)
        {
            @ViewBag.Error = error;
            var md = new MarkdownDeep.Markdown();
            md.ExtraMode = true;
            md.SafeMode = false;
            foreach (var model in models)
            {
                model.Description = md.Transform(model.Description);
            }
            return PartialView(models);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult VoteAnswerUp(AnswerModel item)
        {
            item.Votes += 1;
            return RedirectToAction("VoteAnswer", item);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult VoteAnswerDown(AnswerModel item)
        {
            item.Votes += -1;
            return RedirectToAction("VoteAnswer", item);
        }
        [ValidateInput(false)]
        public ActionResult VoteAnswer(AnswerModel itemModel)
        {
            Guid voterId = Guid.Parse(HttpContext.User.Identity.Name);
            Answer answer = Mapper.Map<AnswerModel, Answer>(itemModel);
            var votes = _unitOfWork.VoteRepository.GetList();
            var voter = votes.FirstOrDefault(x => x.Voter.Id == voterId && x.Answer!=null && x.Answer.Id == answer.Id);
            if (voter != null)
                return RedirectToAction("Details","Question", new { id = itemModel.QuestionId });
            var question = _unitOfWork.QuestionRepository.GetById(itemModel.QuestionId);
            var account = _unitOfWork.AccountRepository.GetById(itemModel.OwnerId);
            answer.Question = question;
            answer.Owner = account;

            
            //answer.Voters.Add(new Vote() { Answer = answer, Voter = voterAccount });
            _unitOfWork.AnswerRepository.Update(answer);
            _unitOfWork.Commit();

            var voterAccount = _unitOfWork.AccountRepository.GetById(voterId);
            _unitOfWork.VoteRepository.Add(new Vote() { Answer = answer, Voter = voterAccount });
            _unitOfWork.Commit();

            Guid idQuestion = Guid.Parse(TempData["id"].ToString());
            return RedirectToAction("Details","Question", new { id = idQuestion });
        }
    }
}

StackOverflow.Web/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StackOverflow.Data;
using StackOverflow.Domain.Entities;
using StackOverflow.Web.Models;

namespace StackOverflow.Web.Controllers
{
    public class CommentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CommentController()
        {
            _unitOfWork = new UnitOfWork();
        }
        // GET: Comment
        public ActionResult CommentIndex(ICollection<CommentListModel> models, string entity)
        {
            @ViewBag.Entity = entity;
            return PartialView(models);
        }
        [Authorize]
        public ActionResult CreateComment(string comment, string AnswerId)
        {
            Guid idQuestion = Guid.Parse(TempData["id"].ToString());
            var question = _unitOfWork.QuestionRepository.GetById(idQuestion);
            Guid creatorId = Guid.Parse(HttpContext.User.Identity.Name);
            var account = _unitOfWork.AccountRepository.GetById(creatorId);

            var newComment = new Comment { Owner = account, Description = comment};
            if (AnswerId != "Question")
            {
                Guid idAnswer = Guid.Parse(AnswerId);
                newComment.Answer = _unitOfWork.AnswerRepository.GetById(idAnswer);
            }
            else
            {
                newComment.Question = question;
            }
            _unitOfWork.CommentRepository.Add(newComment);
            _unitOfWork.Commit();
            
            return RedirectToAction("Details","Question", new { id = idQuestion });
        }
    }
}

StackOverflow.Web/Views/Answer/AnswerIndex.cshtml
@using System.EnterpriseServices
@using StackOverflow.Web.Models
@model IEnumerable<StackOverflow.Web.Models.AnswerModel>


<div class="row">
    <h4>Answers</h4>
    <hr/>
    <ul class="list-group">
        @foreach (var item in Model)
        {
            bool voted = null == item.Voters.FirstOrDefault(x => x.Voter.Id.ToString() == Context.User.Identity.Name);

            <li class="list-group-item col-md-9 ">
                

                @if (item.Correct)
                {
                    <span class="glyphicon glyphicon-ok-sign col-sm-1 " aria-hidden="true"></span>
                }

                <div class="col-md-1">
                   
                    @using (Html.BeginForm("VoteAnswerUp", "Answer", item))
                    {
                        <button type="submit" class="btn btn-default btn-lg row @(voted ? "enabled" : "disabled")" name="1">
                            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                        </button>
                    }
                    <div class="row">
                        <h2>@Html.DisplayFor(modelItem => item.Votes)</h2>
                    </div>
                    @using (Html.BeginForm("VoteAnswerDown", "Answer", item))
                    {
                        <button type="submit" class="btn btn-default btn-lg row @(voted ? "enabled" : "disabled")" name="-1">
                            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
                        </button>
                    }
                </div>


                <div>
                    <div class="col-md-6" >@Html.Raw(@item.Description)</div>
                    <div class="col-md-2">
                        answered by @Html.ActionLink(item.OwnerName, "Profile", "Account", new {id = item.OwnerId}, null)
                        on @Html.DisplayFor(modelItem => item.CreationDate)
                    </div>
                </div>
                <div class="row">
                    @if (TempData["QuestionOwnerId"].ToString() == Context.User.Identity.Name && !((bool) TempData["isAnswered"]))
                    {
                        using (Html.BeginForm("SelectCorrectAnswer", "Question", item))
                        {
                            <div class="form-group">
                                <div>
                                    <input type="submit" value="Set as correct" class="btn btn-success"/>
                                </div>
                            </div>
                        }

                    }
                    @if (item.Correct && TempData["QuestionOwnerId"].ToString() == Context.User.Identity.Name)
                    {
                        using (Html.BeginForm("RemoveCorrectAnswer", "Question", item))
                        {
                            <div class="form-group">
                                <div>
                                    <input type="submit" value="Set as not correct" class="btn btn-danger"/>
                                </div>
                            </div>
                        }
                    }


                </div>
                <div class="row">
                    @{ Html.RenderAction("CommentIndex", "Comment", new {models = item.Comments, entity = item.Id.ToString()});}
                </div>

            </li>
        }
    </ul>
</div>
@using (Html.BeginForm("CreateAnswer","Question"))
{
    <div class="row">
        <h3>Your Answer</h3>

        @*<div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>*@
        <div class="mdd_toolbar"></div>
        @Html.TextArea("description", new {@class = "mdd_editor"});
        <div class="mdd_resizer"></div>
        <div class="mdd_preview"></div>
        @if (ViewBag.Error != null)
        {
            <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Answer" class="btn btn-default"/>
            </div>
        </div>
    </div>
    <script>
        $("textarea.mdd_editor").MarkdownDeep({
            help_location: "/Content/mdd_help.html",
            disableTabHandling: true
        });
    </script>
}